// tests/test_oracle_fixtures.cpp
//
// Compares computeLQR against the pre-generated oracle fixture constants in
// oracle_fixture.h.  The oracle was produced by an independent solver
// (scipy.linalg.solve_continuous_are or a pure-Python sign-function
// fallback); any bug in the C++ Hamiltonian formation or the sign-function
// recovery that the solver tests do not already catch will show here as a
// gain mismatch.
//
// This is a genuine independent-oracle check: the fixture is generated by
// scipy's Schur-based solve_continuous_are (LAPACK), an algorithm independent
// of our Eigen sign-function + Kleinman solver, so agreement rules out a bug
// shared by both.  Measured agreement on the three cascade presets is ~1e-14
// (dK, dP) and ~1e-13 (residual) — i.e. the two algorithms converge on the
// same CARE solution to machine precision.  The relative tolerances below sit
// ~four orders above that measured floor: tight enough that any real regression
// trips them, loose enough to absorb ordinary floating-point/platform variance.
//
// (The absolute-residual assertion at 1e-12 lives in test_lqr.cpp under the
// CARE-hardening ticket; here the relative residual is a secondary sanity bound
// alongside the oracle match.)
//
// Running the oracle generator:
//   cmake --build build --target export_plants
//   ./build/export_plants | python3 tools/gen_oracle_fixtures.py - > tests/oracle_fixture.h

#include "analysis/lqr.h"
#include "analysis/model_library.h"
#include "assert_rel.h"
#include "auto_balance.h"
#include "oracle_fixture.h"
#include "test_helpers.h"

#include <Eigen/Core>
#include <cinttypes>
#include <cstdio>
#include <string>
#include <vector>

using namespace caliburn;

namespace {

// Relative tolerances — the measured floor for K and P agreement is ~1e-14,
// so 1e-10 gives ~four orders of headroom against platform variation.
constexpr double kGainRelTol = 1e-10;
// res.residual is already a dimensionless relative residual; measured ~1e-13.
constexpr double kResRelTol  = 1e-8;

// ── Plant hash (mirrors export_plants.cpp exactly) ───────────────────────────
//
// Replicating these two functions rather than sharing them keeps the test
// self-contained (no Python, no oracle tool at build time) and lets a future
// change to the export format be detected as a hash mismatch before it
// silently corrupts a fixture.

// Full-precision MATLAB-style matrix string — %.17g per element, rows
// separated by "; ", columns by " ".  Must match export_plants.cpp:matrixFull.
std::string matrixFull(const Eigen::MatrixXd& m) {
    std::string s;
    char buf[32];
    for (int r = 0; r < m.rows(); ++r) {
        if (r > 0) s += "; ";
        for (int c = 0; c < m.cols(); ++c) {
            if (c > 0) s += " ";
            std::snprintf(buf, sizeof(buf), "%.17g", m(r, c));
            s += buf;
        }
    }
    return s;
}

// DJB2-64.  Must match export_plants.cpp:djb2_64 exactly.
uint64_t djb2_64(const std::string& s) {
    uint64_t h = 5381;
    for (unsigned char c : s) h = h * 33u + c;
    return h;
}

// Hash A, B, Q, R using the same scheme as export_plants.cpp:makeRecord.
uint64_t hashFor(const LinearSystem& sys,
                 const Eigen::MatrixXd& Q,
                 const Eigen::MatrixXd& R) {
    const std::string combined =
        matrixFull(sys.A) + "|" +
        matrixFull(sys.B) + "|" +
        matrixFull(Q)     + "|" +
        matrixFull(R);
    return djb2_64(combined);
}

// ── Staleness guard ───────────────────────────────────────────────────────────
//
// Recomputes the plant hash from the live plant and compares it to the hash
// baked into oracle_fixture.h.  A mismatch means the plant or weight matrices
// changed without regenerating the fixture; the error message is distinct from
// a numerical-mismatch failure (which reads "FAIL") so the two are told apart.

void checkStaleness(const char* label,
                    const LinearSystem& sys,
                    const LqrPreset& preset,
                    const char* fixture_hash_str) {
    const int n = sys.states();
    const int m = sys.inputs();
    const Eigen::MatrixXd Q = presetStateWeights(preset, n).asDiagonal().toDenseMatrix();
    const Eigen::MatrixXd R = presetInputWeights(preset, m).asDiagonal().toDenseMatrix();

    const uint64_t live = hashFor(sys, Q, R);

    uint64_t stored = 0;
    std::sscanf(fixture_hash_str, "%" SCNx64, &stored);

    if (live != stored) {
        std::fprintf(stderr,
            "STALE FIXTURE [%s]: plant hash mismatch — the plant or weight\n"
            "  matrices changed since oracle_fixture.h was last generated.\n"
            "  fixture hash : %s\n"
            "  live hash    : %016" PRIx64 "\n"
            "  Regenerate:\n"
            "    cmake --build build --target export_plants\n"
            "    ./build/export_plants | python3 tools/gen_oracle_fixtures.py - \\\n"
            "        > tests/oracle_fixture.h\n",
            label, fixture_hash_str, live);
        std::exit(1);
    }

    std::printf("  [%s] hash %s  OK\n", label, fixture_hash_str);
}

// ── Numerical comparison ──────────────────────────────────────────────────────

void checkPreset(const char* label,
                 const LinearSystem& sys,
                 const LqrPreset& preset,
                 const Eigen::MatrixXd& oracle_K,
                 const Eigen::MatrixXd& oracle_P) {
    const int n = sys.states();
    const int m = sys.inputs();

    const Eigen::MatrixXd Q = presetStateWeights(preset, n).asDiagonal().toDenseMatrix();
    const Eigen::MatrixXd R = presetInputWeights(preset, m).asDiagonal().toDenseMatrix();

    const LqrResult res = computeLQR(sys, Q, R);
    ASSERT_TRUE(res.success);

    // Relative Riccati residual: the solver must satisfy the equation it claims
    // to solve.  res.residual is already a dimensionless relative norm.
    ASSERT_REL_NEAR(res.residual, 0.0, kResRelTol);

    // Gain and Riccati solution must agree with the oracle to relative tolerance.
    ASSERT_MATRIX_REL_NEAR(res.K, oracle_K, kGainRelTol);
    ASSERT_MATRIX_REL_NEAR(res.P, oracle_P, kGainRelTol);

    std::printf("  [%s] residual=%.2e  dK=%.2e  dP=%.2e  OK\n",
                label,
                res.residual,
                (res.K - oracle_K).norm(),
                (res.P - oracle_P).norm());
}

}  // namespace

int main() {
    const std::vector<ModelEntry> models = getBuiltinModels();
    const ModelEntry* cascade = nullptr;
    for (const auto& m : models)
        if (isCascadeModel(m)) { cascade = &m; break; }
    if (!cascade) {
        std::fprintf(stderr, "FAIL: no cascade model in the library\n");
        return 1;
    }

    // Staleness checks run first: a stale fixture gives a confusing numerical
    // mismatch, and the error message distinguishes the two failure modes.
    std::printf("Oracle fixture staleness check:\n");
    checkStaleness("Detuned",    cascade->system, lqrPresets()[0],
                   oracle::kHash_cascade_detuned);
    checkStaleness("Nominal",    cascade->system, lqrPresets()[1],
                   oracle::kHash_cascade_nominal);
    checkStaleness("Aggressive", cascade->system, lqrPresets()[2],
                   oracle::kHash_cascade_aggressive);

    std::printf("\nOracle fixture comparison (cascade LQR presets):\n");
    checkPreset("Detuned",    cascade->system,
                lqrPresets()[0],
                oracle::oracle_K_cascade_detuned(),
                oracle::oracle_P_cascade_detuned());

    checkPreset("Nominal",    cascade->system,
                lqrPresets()[1],
                oracle::oracle_K_cascade_nominal(),
                oracle::oracle_P_cascade_nominal());

    checkPreset("Aggressive", cascade->system,
                lqrPresets()[2],
                oracle::oracle_K_cascade_aggressive(),
                oracle::oracle_P_cascade_aggressive());

    std::printf("All oracle fixture tests passed.\n");
    return 0;
}
