#!/usr/bin/env python3
"""gen_oracle_pydrake.py -- Second oracle for CARE fixtures, using pydrake.

Usage (two-step):
    ./export_plants > plants.json
    python3 tools/gen_oracle_pydrake.py plants.json > /tmp/fresh.h

Or pipe directly:
    ./export_plants | python3 tools/gen_oracle_pydrake.py - > /tmp/fresh.h

Reads the JSON emitted by export_plants, solves the continuous-time algebraic
Riccati equation (CARE) for each record using pydrake's Schur-based solver
(pydrake.math.ContinuousAlgebraicRiccatiEquation, backed by LAPACK), and
emits a C++ header in the same format as gen_oracle_fixtures.py so the test
can diff it directly against oracle_fixture.h.

This script is the SECOND oracle.  It shares no algorithm with the C++ sign-
function solver; pydrake's CARE solver is Schur-based (same family as scipy's),
implemented independently in Drake/LAPACK rather than in scipy.  Agreement
between both oracles and the C++ solver gives three-way corroboration.

If pydrake is not installed the script exits with code 1 immediately; the C++
test detects this before running the script and reports a ctest skip instead.
"""

from __future__ import annotations

import json
import sys
from datetime import date

try:
    import numpy as np
    from pydrake.math import ContinuousAlgebraicRiccatiEquation
except ImportError as exc:
    print(f"ERROR: pydrake is not available ({exc})", file=sys.stderr)
    sys.exit(1)


# ── Matrix parsing ───────────────────────────────────────────────────────────

def parse_matlab_matrix(s: str) -> list[list[float]]:
    rows = []
    for row_s in s.split(";"):
        row_s = row_s.strip()
        if not row_s:
            continue
        rows.append([float(x) for x in row_s.split()])
    return rows


# ── CARE solve via pydrake ───────────────────────────────────────────────────

def solve_care_pydrake(A: list, B: list, Q: list, R: list):
    """Solve CARE with pydrake.math.ContinuousAlgebraicRiccatiEquation."""
    A_np = np.array(A)
    B_np = np.array(B)
    Q_np = np.array(Q)
    R_np = np.array(R)
    P_np = ContinuousAlgebraicRiccatiEquation(A_np, B_np, Q_np, R_np)
    return P_np.tolist()


def gain_from_P(P: list, B: list, R: list) -> list:
    """K = R^-1 B^T P"""
    P_np = np.array(P)
    B_np = np.array(B)
    R_np = np.array(R)
    return (np.linalg.solve(R_np, B_np.T @ P_np)).tolist()


# ── C++ header emission ──────────────────────────────────────────────────────

def _ident(name: str) -> str:
    s = name.lower()
    s = s.replace("ball-balancer ", "")
    s = s.replace("/ ", "")
    s = s.replace(" ", "_")
    s = s.replace("-", "_")
    return s.strip("_")


def emit_header(records: list[dict]) -> str:
    import pydrake
    oracle_id = f"pydrake {pydrake.__version__} ContinuousAlgebraicRiccatiEquation (Schur / LAPACK)"

    lines = [
        "// tests/oracle_fixture.h",
        "// Generated by tools/gen_oracle_pydrake.py -- DO NOT EDIT.",
        "// Re-run the pipeline to regenerate:",
        "//   cmake --build build --target export_plants",
        "//   ./build/export_plants | python3 tools/gen_oracle_fixtures.py - > tests/oracle_fixture.h",
        "//",
        f"// Oracle: {oracle_id}",
        f"// Date  : {date.today()}",
        "//",
        "// Each record: K (gain, m x n) and P (Riccati solution, n x n).",
        "// The plant_hash identifies the A, B, Q, R matrices the gain was",
        "// solved against; re-exporting and comparing hashes detects staleness.",
        "#pragma once",
        "",
        "#include <Eigen/Core>",
        "",
        "namespace caliburn::oracle {",
        "",
    ]

    for rec in records:
        ident = _ident(rec["name"])
        A = parse_matlab_matrix(rec["A"])
        B = parse_matlab_matrix(rec["B"])
        Q = parse_matlab_matrix(rec["Q"])
        R = parse_matlab_matrix(rec["R"])

        P = solve_care_pydrake(A, B, Q, R)
        K = gain_from_P(P, B, R)

        n = len(A)
        m = len(R)
        lines += [
            f"// ── {rec['name']} ─────────────────────────────────────────",
            f"// plant_hash : {rec['plant_hash']}",
            f"// K : {m}x{n} gain (u = -K x), P : {n}x{n} Riccati solution",
            "",
            f"inline Eigen::MatrixXd oracle_K_{ident}() {{",
            f"    Eigen::MatrixXd K({m}, {n});",
        ]
        for i in range(m):
            for j in range(n):
                lines.append(f"    K({i}, {j}) = {K[i][j]:.17g};")
        lines += [
            "    return K;",
            "}",
            "",
            f"inline Eigen::MatrixXd oracle_P_{ident}() {{",
            f"    Eigen::MatrixXd P({n}, {n});",
        ]
        for i in range(n):
            for j in range(n):
                lines.append(f"    P({i}, {j}) = {P[i][j]:.17g};")
        lines += [
            "    return P;",
            "}",
            "",
            f"constexpr const char* kHash_{ident} = \"{rec['plant_hash']}\";",
            "",
        ]

    lines += [
        "}  // namespace caliburn::oracle",
        "",
    ]
    return "\n".join(lines)


# ── Entry point ──────────────────────────────────────────────────────────────

def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] == "-":
        data = json.load(sys.stdin)
    else:
        with open(sys.argv[1]) as fh:
            data = json.load(fh)

    print(emit_header(data["records"]), end="")


if __name__ == "__main__":
    main()
